### ISSUE TITLE
Add e2e tests for eventing to workflows.

### ISSUE THREAD

**Issue by vaikas** [mattmoor/mink#101]

**Comment by mattmoor** [comment]
I'd like to just add Eventing to the matrix of tests in this style: https://github.com/mattmoor/mink/pull/105

**Comment by mattmoor** [comment]
Alright, so eventing e2e is in, but I opened this for conformance: https://github.com/mattmoor/mink/issues/115 which is blocked by something upstream.

I've also staged a PR that adds this to Eventing upstream on KinD and varies the `cluster.local` suffix there to avoid baking in assumptions about it, which found an issue 🤩
