### ISSUE TITLE
support creating kind cluster via mink CLI

### ISSUE THREAD

**Issue by mattmoor** [mattmoor/mink#224]

**Comment by csantanapr** [comment]
I want to help on this.

I would also want to have a one liner install script like
```
curl -sL get.mink.dev | sh
```

This should set the smallest resource foot print install, and configure with a knative domain of `127.0.0.1.nip.io` on port 80

**Comment by mattmoor** [comment]
What I was thinking for this was a `mink` command.  I think it'd be fun to then install mink and bootstrap with `get.mink.dev`.

The pieces of what you describe that I sort of have in my mental model are:
1. `mink install --replicas=N` for scaling the control plane.
2. ~`mink kind --nodes=N` for bootstrapping a kind cluster with N nodes/replicas
3. ~`curl get.mink.dev/kind` to install the CLI, and bootstrap a tiny kind cluster

**Comment by csantanapr** [comment]
I think we can have curl get.mink.dev for everything and the default is smallest kind, any variations we do it with env vars

curl ...
HA=3 curl ...
HA=2 KIND=true curl ...

Meaning don't use url path les use env variables pass to script

**Comment by mattmoor** [comment]
Yeah, the path was just a strawman, we can play with our options to see what gives the best UX
