### ISSUE TITLE
Better diagnostic messages when missing flag/configuration

### ISSUE THREAD

**Issue by csantanapr** [mattmoor/mink#267]
first try
```
❯ cd helloworld-go
❯ ls
Dockerfile    go.mod        helloworld.go index.md      service.yaml
❯ mink build
Error: missing field(s): bundle
```
Help spits
```
Usage:
  mink build --image IMAGE [flags]

Examples:

  # Create a build from the context in the current directory and publish
  # it as the provided image name.
  mink build --image docker.io/mattmoor/bundle:latest
```
So I assume I need to specify the image I want to build

Second try
```
❯ mink build --as=me --image docker.io/csantanapr/hello:latest
Error: missing field(s): bundle
```

It looks like I need to specify two images one for bundles and one for the app

**Comment by mattmoor** [comment]
Yeah, so I was wondering to myself why the help text here was so bad, and it's because I abused our `api.ErrMissingField` helpers for constructing errors 🤣 

Let's use this issue to track fixing that. 🤦
