### ISSUE TITLE
mink build on GCP using workload identity fails to create the Task pod

### ISSUE THREAD

**Issue by jstrachan** [mattmoor/mink#277]
mink looks great but I can't figure out how to use the source bundles in my GCP cluster.

I get this error inside tekton controller when I try `mink build`; the container image is created for the source bundle but tekton (0.18.0) refuses to make the pod. I wonder if you had any ideas?

```
failed to create task run pod \"dockerfile-rsl95\": translating TaskSpec to Pod: error getting image manifest: GET https://gcr.io/v2/jenkins-x-labs-bdd/helloworld-go-bundle/manifests/sha256:5af1ada1fb26e1b8214b4480dff034931e584ebe7d79d32d61619a64e4b91836: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication. Maybe invalid TaskSpec
```
The source bundle is created fine; its tekton not being able to make the `Pod` from the `TaskRun`

It seems that because the source bundle step doesn't have a command, tekton controller tries to load the image details to discover the entrypoint: https://github.com/tektoncd/pipeline/blob/e2f528b0b247efb3b52b10800aad4ffd9046a266/pkg/pod/entrypoint_lookup_impl.go#L80 which seems to barf in my cluster. So the `Pod` is never created for the `TaskRun`.

I wonder if some IAM roles need to be added to the tekton controller service account to be able to query image metadata from GCR or something?

I'm using workload identity on my GCP cluster; I can build images fine with the same `ServiceAccount` I pass into `mink build` which is used on the `TaskRun`. It looks like `tekton-controller` is doing some kind of validation on the image and deciding not to even try to create the Pod I think?

Whats odd is I can build and deploy private images just fine on this cluster using the same GCP project. Other than the `ServiceAccount` I don't see any other auth related things on the `TaskRun` and I can, in the same namespace, create `PipelineRuns` which write to the same GCR registry.

**Comment by mattmoor** [comment]
So the way workload identity works is by masking the `http://metadata` endpoint exposed to the Node from being visible to the Pods, and replacing it with its own.  This means that pods trying to interact with image registries for metadata resolution in the same way as the kubelet (e.g. via ggcr + k8schain) will run afoul of the asymmetric auth between the Pod and Node.

However, this should be a problem for Tekton with any private image in your GCR repository.  Have you tried running any custom container image (hosted in this GCR repo) as a step?  My phases of reaction to this were:
1. Yes ofc that's the problem
2. No that couldn't be the problem, it'd break ALL custom steps
3. Maybe that's the problem, custom steps aren't THAT common 🤔 

So something to try would be to `crane cp <public image> <your gcr repo>` and run that as a step in a TaskRun to see whether mink is the problem at all.

In the meantime, I'll try to set up a similar environment to repro this.  thanks!

cc @imjasonh since this may impact tekton more broadly on GKE.

**Comment by ImJasonH** [comment]
https://github.com/tektoncd/pipeline/issues/3208

**Comment by mattmoor** [comment]
I was able to reproduce this on my cluster, and I suspect that we need to run something like this:
```
# Create mink-controller IAM SA in the current project
gcloud iam service-accounts create mink-controller

# Grant registry read access to this IAM SA.
gcloud projects add-iam-policy-binding $(gcloud config get-value core/project) \
    --member=serviceAccount:mink-controller@$(gcloud config get-value core/project).iam.gserviceaccount.com \
    --role=roles/storage.objectViewer

# Allow the mink-system/controller SA to impersonate the above SA
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$(gcloud config get-value core/project).svc.id.goog[mink-system/controller]" \
  mink-controller@$(gcloud config get-value core/project).iam.gserviceaccount.com
```

I'm still sorting out the exact commands, since that doesn't work (or has some sort of propagation delay)

**Comment by mattmoor** [comment]
cc @mikedanese @cjcullen 

Anything obvious I'm missing? 🤔

**Comment by mattmoor** [comment]
Ok, so with this one final bit things got to the build itself (which I didn't setup auth for, so it failed, but it pulled!):
```
kubectl annotate serviceaccount \
  --namespace mink-system \
  controller \
  iam.gke.io/gcp-service-account=mink-controller@$(gcloud config get-value core/project).iam.gserviceaccount.com
```

**Comment by jstrachan** [comment]
I tried the above steps with the tekton 1.18.0 controller so the last bit was...

```
kubectl annotate serviceaccount \
  --namespace tekton-pipelines \
  tekton-pipelines-controller \
  iam.gke.io/gcp-service-account=mink-controller@$(gcloud config get-value core/project).iam.gserviceaccount.com
```

and I see the annotation on the tekton-pipelines-controller SA but still get the same error

**Comment by mattmoor** [comment]
For Tekton the binding step should be:
```
# Allow the mink-system/controller SA to impersonate the above SA
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$(gcloud config get-value core/project).svc.id.goog[tekton-pipelines/tekton-pipelines-controller]" \
  mink-controller@$(gcloud config get-value core/project).iam.gserviceaccount.com
```

Just want to confirm that (note the `[tekton-pipelines/tekton-pipelines-controller]`)

**Comment by jstrachan** [comment]
doh! that was it - many thanks!!!

**Comment by mattmoor** [comment]
Cool, I get some docs going.

**Comment by ImJasonH** [comment]
FWIW @navidz has some ideas about how Tekton can avoid having to give the controller SA permission to read all step images, which could be problematic in a multi tenant environment. This should incidentally also make WI work without these steps.

**Comment by mattmoor** [comment]
Can you loop me into those conversations?

**Comment by NavidZ** [comment]
The conversations were mostly verbal :).
However, let me create an issue in Tekton repository and describe my thought process there. I'll cc you as well there.
