### ISSUE TITLE
Fix multi-arch ko build in CI

### ISSUE THREAD

**Issue by mattmoor** [mattmoor/mink#342]
It looks like the multi-arch `ko` image is failing some builds in CI because the `registry:2` image doesn't allow foreign layers by default.

@jonjohnsonjr pointed me to: https://github.com/docker/distribution/pull/2035#issuecomment-297792176

We should be able to disable validation in CI: https://github.com/docker/distribution/blob/master/docs/configuration.md#urls

We would need to pass a custom config file here: https://github.com/mattmoor/mink/blob/658431cc66d92f5a155480590250da7e8dd18939/hack/setup-kind.sh#L198

**Comment by mattmoor** [comment]
cc @tcnghia was experimenting with configuring the registry at one point 🥺

**Comment by tcnghia** [comment]
I saw some doc here https://docs.docker.com/registry/configuration/#overriding-the-entire-configuration-file
