### ISSUE TITLE
Premature end while befor TaskRun started

### ISSUE THREAD

**Issue by kameshsampath** [mattmoor/mink#357]
When we use command like :
```shell 
mink buildpack --image=kind-registry.local:5000/kameshsampath/quarkus-mink \
  --bundle=kind-registry.local:5000/kameshsampath/quarkus-mink-bundle \
  --builder=quay.io/kameshsampath/java-11-jvm-builder \
  --directory=myappdir
```
When the command starts for  the first time, it will take few seconds/mins for the TaskRun to run, but `mink` ends prematurely with the error `task Task 0 create has not started yet or pod for task not yet available` but if you do `tkn tr ls` it still reports TaskRun waiting to start. 

Its better that we wait for the TaskRun state to be `running` or  `failed` before we start to stream the log.

CC: @csantanapr

**Comment by mattmoor** [comment]
I am fairly certain that is coming from this Tekton package that we're calling: https://github.com/tektoncd/cli/blob/fcf584dbd63721e1e5c8185a145b30cd1321b203/pkg/cmd/taskrun/logs.go#L92

The error is surfaced here after some timeout: https://github.com/tektoncd/cli/blob/fcf584dbd63721e1e5c8185a145b30cd1321b203/pkg/log/task_reader.go#L230

Which is hard coded to 10 seconds 🤣 
https://github.com/tektoncd/cli/blob/fcf584dbd63721e1e5c8185a145b30cd1321b203/pkg/log/task_reader.go#L80

**Comment by kameshsampath** [comment]
I tried to reproduce this to see why that happens, as you pointed @mattmoor the log reads is causing the issue, but just only once possibly pulling images 🤔; but during debug cant figure that as it passes on. Every time to reproduce I have delete cluster and registry and start fresh 😅

**Comment by mattmoor** [comment]
Once the linked PR lands upstream, we can start setting this downstream to something higher.

I also think this should start happening less with what's at HEAD because I switched to the (new?) `/cnb/lifecycle/creator` entrypoint, so there are fewer active containers in the buildpacks pod.

**Comment by mattmoor** [comment]
This merged upstream
