### ISSUE TITLE
Enable auto-TLS with HTTP01 out of the box

### ISSUE THREAD

**Issue by mattmoor** [mattmoor/mink#4]
Here's what I'm thinking:
- Dump the namespace certificate controller (only makes sense with a DNS01 solver).
- Link a simple HTTP01 challenge solver (to avoid the full cert-manager dependency)
- Enable auto-TLS out-of-the-box (leaving HTTP open).

The intent of this is to effectively make enabling DNS/TLS a simple two step process:
1. Configure your DNS to the ingress IP,
2. Change config-domain to use the domain configured above.

cc @zhiminxiang FYI

**Comment by ZhiminXiang** [comment]
SGTM.
I haven't tried but looks like this binary (https://github.com/jetstack/cert-manager/blob/master/cmd/acmesolver/main.go) is for HTTP01 challenge.
I will try it when I get a chance.
