### ISSUE TITLE
Docs: Can we add docs to guide how to use mink 

### ISSUE THREAD

**Issue by PuneetPunamiya** [mattmoor/mink#446]
Can we have a guide/docs which gives a complete guide of how mink can be used, with some guideline of how mink can help to install a resource

**Comment by vincent-pli** [comment]
@mattmoor agree with @PuneetPunamiya 
I jump from https://github.com/knative/pkg/issues/1181
and https://github.com/tektoncd/pipeline/issues/3404

try to figure out what's the Mink ready does, since we hit some performance issue for `tekton`.

**Comment by mattmoor** [comment]
mink uses Knative's statefulset-based sharding logic to split the way resources are handled over the statefulset's replicas.

If you use:
```
mink install --replicas 4
```

mink configures the control plane to run 4 replicas, each of which processes ~1/4 of the resources.

**Comment by vincent-pli** [comment]
@mattmoor that's great.
if that means `controller` based on `knative/pkg` has such ability? and do we have any document for implements details, thanks
